version: "3.8"
services:
  configserver:
    image: sereybank/configserver:latest
    mem-limit: 700m
    ports:
      - "8071:8071"
    networks:
      - sereynetwork
  accounts:
    image: sereybank/accounts:latest
    mem-limit: 700m
    ports:
      - "8080:8080"
    networks:
      - sereynetwork
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
networks:
  sereynetwork: